### ISSUE TITLE
显卡不兼容（疑似）

### ISSUE THREAD

**Issue by fengsui9528** [friendlyhj/FlyingRoad-4#1]
[https://paste.ubuntu.com/p/VPNdFfrk3d/](url)
正常启动游戏（源文件并没动），9/7的时候崩溃提示
(PCL2的提示:你的显卡驱动存在问题，导致游戏无法正常运行。
请尝试升级你的显卡驱动到最新版本，或回退到出厂版本，然后再启动游戏。
如果还是不行，可以尝试使用8.0.51或更低版本的Java。
如果问题依然存在，那么你可能需要换个更好的显卡...
如果要寻求帮助，请向他人发送错误报告文件，而不是发送这个窗口的截图。
)
尝试更新显卡驱动（现546.01）无法启动
更新到551.52也同样崩溃
时不时还可以进入游戏，崩溃十几次才能进一次都很正常
（java版本17.0.6）
PCL2提示的8.0.51也同样尝试过
我电脑配置：
12600KF+4070
（qq不敢@怕打扰你）

**Comment by friendlyhj** [comment]
先尝试移除 Better Loading Screen，后尝试再移除 Modern UI
